import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../componets/header/header.js";
import ChatButton from "../componets/chatbutton/ChatButton.js";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "../componets/footer/footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Final Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main style={{ flex: 1 }}>{children}</main>
          <ChatButton />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
